<template><section><h2>tooltips组件</h2>
<h3>基础用法</h3>
<demo-block class="demo-box">
                    <div class="source"><template>
<div style="position: relative; width: 400px; margin: 20px auto; height:200px;">
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="left up" style="position: absolute;left:-40px;top:20px;"><sf-button>左上</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="left" style="position: absolute;left:-40px;top:80px;"><sf-button>左中</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="left down" style="position: absolute;left:-40px;top:140px;"><sf-button>左下</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="up left" style="position: absolute;left:40px;top: 0px;"><sf-button>上左</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="up" style="position: absolute;left:140px;top: 0px"><sf-button>上中</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="up right" style="position: absolute;left:240px;top: 0px;"><sf-button>上右</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="right up" style="position: absolute;left:320px;top: 20px;"><sf-button>右上</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="right" style="position: absolute;left:320px;top: 80px;"><sf-button>右中</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="right down" style="position: absolute;left:320px;top:140px;"><sf-button>右下</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="down left" style="position: absolute;left:40px;top:160px;"><sf-button>下左</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="down" style="position: absolute;left:140px;top:160px;"><sf-button>下中</sf-button></sf-tooltips>
		<sf-tooltips content="<p>tooltips hello</p><p>tooltips hello</p>" placement="down right" style="position: absolute;left:240px;top:160px;"><sf-button>下右</sf-button></sf-tooltips>
</div>
</template>



</div>
                    <div class="meta">
                      <div class="description"><p>sf-tooltips组件。</p>
</div>
                      <div class="highlight"><pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">template</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">div</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: relative; width: 400px; margin: 20px auto; height:200px;"</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"left up"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:-40px;top:20px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>左上<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"left"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:-40px;top:80px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>左中<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"left down"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:-40px;top:140px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>左下<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"up left"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:40px;top: 0px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>上左<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"up"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:140px;top: 0px"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>上中<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"up right"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:240px;top: 0px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>上右<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"right up"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:320px;top: 20px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>右上<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"right"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:320px;top: 80px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>右中<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"right down"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:320px;top:140px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>右下<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"down left"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:40px;top:160px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>下左<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"down"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:140px;top:160px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>下中<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">sf-tooltips</span> <span class="hljs-attr">content</span>=<span class="hljs-string">"&lt;p&gt;tooltips hello&lt;/p&gt;&lt;p&gt;tooltips hello&lt;/p&gt;"</span> <span class="hljs-attr">placement</span>=<span class="hljs-string">"down right"</span> <span class="hljs-attr">style</span>=<span class="hljs-string">"position: absolute;left:240px;top:160px;"</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">sf-button</span>&gt;</span>下右<span class="hljs-tag">&lt;/<span class="hljs-name">sf-button</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">sf-tooltips</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">div</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">template</span>&gt;</span>

<span class="hljs-tag">&lt;<span class="hljs-name">script</span>&gt;</span><span class="undefined">

</span><span class="hljs-tag">&lt;/<span class="hljs-name">script</span>&gt;</span>

</code></pre>
</div></div></demo-block>
</section></template>

<script>

</script>